
DATASET:
  subjects:
    - Popo
    - Hadia
    - Karl
    - Locky
    - Storma
    - Jawie
  bhv_category:
    - moving
    - resting
    - feeding
    - grooming
    - exploring
    - playing
    - social-playing
    - social
    - interacting with public
    - sex
    - agonistic
  macro_bhv:
    - Individual
    - Social
    - Social-Ludic
    - Ludic
    - Sexual
    - Agonistic
    - Public
  periods:
    - pregame
    - game
    - postgame

COLORS:
  layout:
    primaryColor: "#FF8C8C"
    backgroundColor: "#313B2F"
    secondaryBackgroundColor: "#52675B"
    textColor: "#E4E4E4"
  behaviors:
    Social: "#C5D845"
    Ludic: "#6CB44A"
    Social-Ludic: "#1D9237"
    Agonistic: "#9B5454"
    Public: "#D67C7A"
    Individual: "#86BDB2"
    Sexual: "#538A6B"
  bhv_highlight:
    Social: "#FFF7CF"
    Ludic: "#CCFFED"
    Social-Ludic: "#B8EA91"
    Agonistic: "#D2A78E"
    Public: "#F6CAE0"
    Individual: "#B7D6FB"
    Sexual: "#ABD7BA"
  periods:
    pregame: "#C5D845"
    game: "#6CB44A"
    postgame: "#1D9237"

DESC:
  Karl: "Dominant male. Father of Popo and Hadia. 
           Sexually compulsive (when he takes a female 
           he retains her for a long time). He is very 
           intelligent but not very active."
  Popo: "Locky and Karl son. He is becoming an adult 
           and begins to have sexual behaviors with the 
           whole group, as simulated behaviors). He is 
           very active, usually in a positive way. He 
           does not trust his father because he is 
           aggressive with him."
  Hadia: "Daughter of Jawie and Karl. When she doesn't get what 
            she wants (food, play, enrichment...) she throws 
            tantrums as if she was a human baby (she screams 
            and moves compulsively). Apart from that, she is
            calm and has a very good relationship with her grandmother, Locky."
  Jawie: "Daughter of Locky and Karl. She is Locky's first 
            daughter and a good but unloving mother. She has 
            a somewhat rough relationship with humans 
            (with almost everyone, except for some keepers)."
  Storma: "She is the only one that comes from another zoo. 
             She has been very distrustful and it has been difficult
             for her to adapt, although from the first moment she 
             has had a good relationship with everyone. She is very 
             impulsive with food and has Locky as a foster mother."
  Locky: "Old female. Mother of Jawie and Popo. 
            She is very pacifying and protective 
            with her son Popo. She has a respectful relationship
            with Jawie but since she became a mother they are a
            little bit more distant emotionally. She's been like an
            adoptive mother for Storma. Everyone else has her as a 
            safety reference."
  All: "Lorem ipsum"
