
DATASET:
  subjects:
    - Karl
    - Hadia
    - Popo
    - Locky
    - Storma
    - Jawie
  bhv_category:
    - moving
    - resting
    - feeding
    - grooming
    - exploring
    - playing
    - social-playing
    - social
    - interacting with public
    - sex
    - agonistic
  macro_bhv:
    - Individual
    - Social
    - Social-Ludic
    - Ludic
    - Sex
    - Agonistic
    - Public

COLORS:
  layout:
    primaryColor: "#FF8C8C"
    backgroundColor: "#313B2F"
    secondaryBackgroundColor: "#52675B"
    textColor: "#E4E4E4"
  behaviors:
    Social: "#C5D845"
    Ludic: "#6CB44A"
    Social-Ludic: "#1D9237"
    Agonistic: "#9B5454"
    Public: "#D67C7A"
    Individual: "#86BDB2"
    Sex: "#538A6B"
